mystr = 'Beautiful is better than ugly'
print('source string is: ',mystr)
print('swapcase demo\t',mystr.swapcase())
print('upper demo\t',mystr.upper())
print('lower demo\t',mystr.lower())
print('title demo\t',mystr.title())
print('istitle demo\t',mystr.istitle())
print('islower demo\t',mystr.islower())
print('capitalize demo\t',mystr.capitalize())
print('find demo\t',mystr.find('u'))
print('count demo\t',mystr.count('a'))
print('split demo\t',mystr.split(' '))
print('join demo\t',' '.join('abcde'))
print('len demo\t',len(mystr))

